### ISSUE TITLE
Getting Invalid character error on IE 11 

### ISSUE THREAD

**Issue by chintan-peaas** [sindresorhus/public-ip#24] opened 2018-09-19 09:36 UTC
I'm facing the same issue as https://github.com/sindresorhus/public-ip/issues/18. I'm trying to get the client IP in the front-end code using public-ip and it's causing Invalid character issue in IE. In other browsers, it works fine.

@sindresorhus  commented on that issue and as per the comment, I tried [babel-engine-plugin](https://github.com/SamVerschueren/babel-engine-plugin), but that also didn't work. It still gives the same error.

**Comment by sindresorhus** [comment] 2018-09-19 09:59
Duplicate of #18

**Comment by sindresorhus** [comment] 2018-09-19 09:59
As commented in #18, it's up to you to transpile for browser support.

**Closed by sindresorhus** 2018-09-19 09:59 UTC

**Comment by chintan-peaas** [comment] 2018-09-19 10:04
Yes, but can you throw some light on how to do that? I tried the babel-engine-plugin, but it didn't work. Please advise.
